#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
	# set spacevim theme. by default colorscheme layer is not loaded,
	# if you want to use more colorscheme, please load the colorscheme
	# layer
	colorscheme = "dracula"
	colorscheme_bg = "dark"
	# Disable guicolors in basic mode, many terminal do not support 24bit
	# true colors
	enable_guicolors = true
	# Disable statusline separator, if you want to use other value, please
	# install nerd fonts
	statusline_separator = "arrow"
	statusline_iseparator = "arrow"
	buffer_index_type = 4
	enable_tabline_filetype_icon = true
	enable_statusline_mode = false

	# Tab 键 size
	default_indent = 2
	expand_tab = false

	vim_help_language = "cn"

	# 文件树 NerdTree 位置放到左边
  filetree_direction = 'left'

# Enable autocomplete layer
[[layers]]
	name = 'autocomplete'
	auto_completion_return_key_behavior = "complete"
	auto_completion_tab_key_behavior = "smart"

[[layers]]
	name = 'shell'
	default_position = 'bottom'
	default_height = 30

# 类似于 spotlight
[[layers]]
  name = "telescope"

[[layers]]
  name = "chinese"

# js
# eslint: npm install -g eslint-cli
# js-beautify: npm install -g js-beautify
[[layers]]
	name = "lang#javascript"
	auto_fix = true
  enable_flow_syntax = true

# ts
# tsfmt: npm install -g typescript-formatter
# eslint: npm install -g eslint
[[layers]]
	name = "lang#typescript"

# dart
[[layers]]
	name = "lang#dart"

[[layers]]
  name = "tools"

[[layers]]
	name = "format"

[[layers]]
	name = 'git'

[[layers]]
  name = "lsp"

[[layers]]
  name = "treesitter"

[[layers]]
  name = "ui"
  enable_sidebar = false
  enable_scrollbar = false
  enable_indentline = true
  enable_cursorword = false
  indentline_char = '|'
  conceallevel = 0
  concealcursor = ''
  cursorword_delay = 50
  cursorword_exclude_filetype = []
  indentline_exclude_filetype = []

[[layers]]
  name = "VersionControl"

# ----- 插件: 主题 ----- #
[[custom_plugins]]
  name = "dracula/vim"
# ----- 插件: 主题 ----- #

# ----- 插件: lsp https://github.com/natebosch/vim-lsc ----- #
[[custom_plugins]]
  name = "natebosch/vim-lsc"
	merged = false
# ----- 插件: dart lsp https://github.com/natebosch/vim-lsc ----- #

# ----- 插件: dart 语法高亮/检测等 https://github.com/dart-lang/dart-vim-plugin ----- #
[[custom_plugins]]
  name = "dart-lang/dart-vim-plugin"
	merged = false
# ----- 插件: dart 语法高亮/检测等 https://github.com/dart-lang/dart-vim-plugin ----- #

# ----- 插件: dart lsp https://github.com/natebosch/vim-lsc-dart ----- #
[[custom_plugins]]
  name = "natebosch/vim-lsc-dart"
	merged = false
# ----- 插件: dart lsp https://github.com/natebosch/vim-lsc-dart ----- #

# ----- 插件: dart hot-reload-on-save https://github.com/thosakwe/vim-flutter ----- #
[[custom_plugins]]
	repo = "thosakwe/vim-flutter"
	merged = false
# ----- 插件: dart hot-reload-on-save https://github.com/thosakwe/vim-flutter ----- #